name: Build and run examples

on: [push, pull_request]

jobs:
  windows:
    name: Windows Visual Studio ${{ matrix.version }}
    runs-on: windows-${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        version: [2019, 2022]
    steps:
      - uses: microsoft/setup-msbuild@v1.1
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cd issues/dscp/qos2-windows/
          cmake .
          msbuild Examples.sln /m /property:Configuration=Debug
      - name: Get user
        run: |
          Get-LocalUser
      - name: Check admin
        run: |
          Get-LocalGroupMember -Group "Administrators"
      - name: Check network operators
        run: |
          Get-LocalGroupMember -Group "Network Configuration Operators"
      - name: Run
        run: |
          Add-LocalGroupMember -Group "Network Configuration Operators" -Member "$env:UserName" -Verbose
          issues\dscp\qos2-windows\Debug\qos-test.exe
      - name: Check network operators after
        run: |
          Get-LocalGroupMember -Group "Network Configuration Operators"
